/**
 * The generated, human-readable view of a run.
 *
 * CAPO's sessions are headless child processes: they never appear in a host's
 * session list and there is no window to open. `capo status` is one way in,
 * and this file is the other, refreshed on every state change so someone can
 * watch a run with `tail -f` or just open it in an editor.
 *
 * It is a view, always rebuildable from `state.json`. Nothing reads it back.
 */
import type { RunState } from '../types.js';

export function renderStatusMarkdown(state: RunState): string {
  const lines: string[] = [];

  lines.push(`# Run ${state.runId}`);
  lines.push('');
  lines.push(`- status: **${state.status}**`);
  lines.push(`- active platform: **${state.activePlatform}**`);
  lines.push(`- pauses so far: ${state.pauseCount}`);
  lines.push(`- base commit: ${state.baseCommit || '(not yet set)'}`);
  lines.push(`- started: ${state.startedAt}`);
  lines.push(`- updated: ${state.updatedAt}`);
  lines.push('');

  lines.push('## Sessions');
  lines.push('');
  const sessions = Object.values(state.sessions);
  if (sessions.length === 0) {
    lines.push('_none running_');
  } else {
    lines.push('| session | role | platform | status | stalled | platform session id |');
    lines.push('| --- | --- | --- | --- | --- | --- |');
    for (const s of sessions) {
      const stalled = s.stalled ? `yes, since ${s.stalledSince ?? 'unknown'}` : 'no';
      lines.push(
        `| ${s.id} | ${s.role} | ${s.platform} | ${s.status} | ${stalled} | ${s.platformSessionId ?? '-'} |`,
      );
    }
    lines.push('');
    lines.push(
      'The platform session id is that platform\'s own id for the conversation. ' +
        'For Claude Code it is the `--session-id` CAPO generated, so `claude --resume <id>` ' +
        'should reopen it.',
    );
  }
  lines.push('');

  lines.push('## Tasks');
  lines.push('');
  const tasks = Object.values(state.tasks);
  if (tasks.length === 0) {
    lines.push('_no tasks registered yet_');
  } else {
    lines.push('| task | coordinator | state | write scope | result |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const t of tasks) {
      lines.push(
        `| ${t.id} | ${t.coordinator} | ${t.state} | ${t.writeScope.join(', ')} | ${t.resultCommit ?? '-'} |`,
      );
    }
  }
  lines.push('');

  const limits = Object.entries(state.limits);
  if (limits.length > 0) {
    lines.push('## Usage limits seen');
    lines.push('');
    for (const [platform, limit] of limits) {
      const reset = limit.resetAt ?? 'unknown';
      lines.push(`- **${platform}**: detected ${limit.detectedAt}, resets ${reset}`);
      lines.push(`  - reported as: ${limit.raw}`);
    }
    lines.push('');
  }

  if (state.status === 'waiting') {
    lines.push('> Every platform is capped. The run is parked, not dead.');
    lines.push('> Continue it with `capo resume ' + state.runId + '`.');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('Generated by CAPO. Rebuilt on every state change; edits are overwritten.');
  lines.push('');
  return lines.join('\n');
}
